version: "3.9"

services:
  django_gunicorn:
    build: .
    volumes:
      - static:/static
    ports:
      - "8000:8000"
    env_file:
      - .env
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
    links:
      - django_gunicorn

volumes:
  static: