# Generated by Django 4.1.7 on 2023-04-06 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='stocker.stock'),
        ),
    ]
