# Generated by Django 4.1.7 on 2023-04-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocker', '0002_alter_news_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
