# Generated by Django 4.1.7 on 2023-03-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('device_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=4)),
                ('priority', models.IntegerField()),
                ('selected', models.BooleanField()),
            ],
        ),
    ]
