# Generated by Django 4.1.7 on 2023-03-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klcovany', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='selected',
            new_name='is_selected',
        ),
    ]
