# Generated by Django 4.1.7 on 2023-03-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klcovany', '0002_rename_selected_device_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='consumption',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
