# Generated by Django 4.1.7 on 2023-03-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klcovany', '0005_remove_plant_last_devices_refresh_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='consumption',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
