# Generated by Django 4.1.7 on 2023-04-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klcovany', '0008_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_id',
            new_name='external_id',
        ),
    ]
